models:
  qwen3.5-9b:
    model_name: Qwen/Qwen3.5-9B
    model_type: openai
    base_url: https://api.together.xyz/v1
    api_key_env: TOGETHER_API_KEY
    logprobs: true
    top_logprobs: 5
    extra_body:
      reasoning:
        enabled: false
    max_retries: 30
    backoff: 1.5
    input_cost_per_million_usd: 0.10
    output_cost_per_million_usd: 0.15

  deepseek-v3.2:
    model_name: deepseek-reasoner
    model_type: openai
    base_url: https://api.deepseek.com
    api_key_env: DEEPSEEK_API_KEY
    extra_body:
      reasoning:
        enabled: true
    max_retries: 30
    backoff: 1.5
    input_cost_per_million_usd: null
    output_cost_per_million_usd: null

  qwen-plus:
    model_name: qwen/qwen3-235b-a22b-2507
    model_type: openai
    base_url: https://openrouter.ai/api/v1
    api_key_env: OPENROUTER_API_KEY
    max_retries: 30
    backoff: 1.5
    input_cost_per_million_usd: null
    output_cost_per_million_usd: null
